Update 42vmapper

diff --git a/scrips/42vmapper b/scrips/42vmapper
--- a/scrips/42vmapper
+++ b/scrips/42vmapper
@@ -235,7 +235,7 @@ else
       log_msg 2 "vmapper.sh downloaded"
       echo "`date +%Y-%m-%d_%T` 42vmapper: Installed vmapper.sh, from vmconf develop !!"  >> $logfile
     else
-      until /system/bin/curl -s -k -L --fail --show-error -o /system/bin/vmapper.sh https://raw.githubusercontent.com/ReuschelCGN/aconf/tree/vconf/scrips/vmapper.sh || { echo "`date +%Y-%m-%d_%T` 42vmapper: Download vmapper.sh failed for origin=$origin, auth=$auth, server=$server from ip=$ip. Exit script" >> $logfile ; exit 1; } ;do
+      until /system/bin/curl -s -k -L --fail --show-error -o /system/bin/vmapper.sh https://raw.githubusercontent.com/ReuschelCGN/aconf/vconf/scrips/vmapper.sh || { echo "`date +%Y-%m-%d_%T` 42vmapper: Download vmapper.sh failed for origin=$origin, auth=$auth, server=$server from ip=$ip. Exit script" >> $logfile ; exit 1; } ;do
         sleep 2
       done
       chmod +x /system/bin/vmapper.sh
@@ -268,7 +268,7 @@ else
       log_msg 2 "ATVdetailsSender.sh downloaded"
       echo "`date +%Y-%m-%d_%T` 42vmapper: Installed ATVdetailsSender.sh, from vmconf develop !!"  >> $logfile
     else
-      until /system/bin/curl -s -k -L --fail --show-error -o /system/bin/ATVdetailsSender.sh https://raw.githubusercontent.com/ReuschelCGN/aconf/tree/vconf/scrips/ATVdetailsSender.sh || { echo "`date +%Y-%m-%d_%T` 42vmapper: Download ATVdetailsSender.sh failed for origin=$origin, auth=$auth, server=$server from ip=$ip. Exit script" >> $logfile ; exit 1; } ;do
+      until /system/bin/curl -s -k -L --fail --show-error -o /system/bin/ATVdetailsSender.sh https://raw.githubusercontent.com/ReuschelCGN/aconf/vconf/scrips/ATVdetailsSender.sh || { echo "`date +%Y-%m-%d_%T` 42vmapper: Download ATVdetailsSender.sh failed for origin=$origin, auth=$auth, server=$server from ip=$ip. Exit script" >> $logfile ; exit 1; } ;do
         sleep 2
       done
       chmod +x /system/bin/ATVdetailsSender.sh
